name: Performs spelling and grammar checks on the libjpel.so blog

on: push

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: jpellman/blog-gramma@v1
    - uses: jpellman/blog-aspell@v1
